### ISSUE TITLE
Update to Laravel 10?

### ISSUE THREAD

**Issue by ITrunsDE** [artkonekt/opsgenie-laravel#3]
Is an update to Laravel 10 on your roadmap?

**Comment by fulopattila122** [comment]
Thanks for pinging. Now it's on the roadmap :)

**Comment by fulopattila122** [comment]
Version [1.2.0](https://github.com/artkonekt/opsgenie-laravel/blob/master/Changelog.md#120) supports Laravel 10.

Thanks again for pinging! :tada:

**Comment by ITrunsDE** [comment]
That is so great. Thank you very much.
